version: '3.8'

services:

  # --- PostgreSQL for user-service ---
  user-service-db:
    image: postgres:15
    container_name: user-service-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata_user:/var/lib/postgresql/data

  # --- PostgreSQL for user-man-service ---
  user-man-service-db:
    image: postgres:15
    container_name: user-man-service-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: usermandb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata_userman:/var/lib/postgresql/data

  # --- PostgreSQL for stats-service ---
  stats-service-db:
    image: postgres:15
    container_name: stats-service-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: statsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata_stats:/var/lib/postgresql/data

  # --- Shared RabbitMQ ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata_user:
  pgdata_userman:
  pgdata_stats:   # <-- Added missing volume
