openapi: 3.0.3
info:
  title: Role Service API
  version: 1.0.0
  description: Assigns and manages user roles.

paths:
  /roles/{userId}:
    get:
      summary: Get roles for a user
      operationId: getRolesForUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Roles retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRolesResponse'
        '404':
          description: User not found or no roles

components:
  schemas:
    # --- Event from user-man-service ---
    UserCreatedEvent:
      x-event: true
      type: object
      required:
        - userId
        - email
        - createdAt
      properties:
        userId:
          type: string
          format: uuid
        email:
          type: string
          format: email
        createdAt:
          type: string
          format: date-time

    # --- Optional event emitted by role-service ---
    RoleAssignedEvent:
      x-event: true
      type: object
      required:
        - userId
        - email
        - roles
      properties:
        userId:
          type: string
          format: uuid
        email:
          type: string
        roles:
          type: array
          items:
            type: string
          example: [ "ROLE_USER" ]

    # --- REST Response DTO ---
    UserRolesResponse:
      type: object
      required:
        - userId
        - roles
      properties:
        userId:
          type: string
          format: uuid
        roles:
          type: array
          items:
            type: string
            example: ROLE_USER
