openapi: 3.0.3
info:
  title: Stats Service API
  version: 1.0.0
  description: Tracks system-wide statistics like total user registrations.

paths:
  /stats/registrations:
    get:
      summary: Get total registered users
      operationId: getTotalRegistrations
      responses:
        '200':
          description: Total registrations retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TotalRegistrationsResponse'

components:
  schemas:
    TotalRegistrationsResponse:
      type: object
      required:
        - total
      properties:
        total:
          type: integer
          format: int32
          example: 1234

    # Event from user-man-service
    UserCreatedEvent:
      x-event: true
      type: object
      required:
        - userId
        - email
        - createdAt
      properties:
        userId:
          type: string
          format: uuid
        email:
          type: string
          format: email
        createdAt:
          type: string
          format: date-time
