version: "3.8"
services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_PORT: 5672
    logging:
      driver: "none" # Suppress logs
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      timeout: 5s

  publisher1:
    image: lab1-app:latest
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - APPLICATION_ID=publisher1
      - APPLICATION_MODE=publisher
      - PUBLISH_EVENT=Type1Event
      - PUBLISHER_TYPE=interval
      - PROCESSING_TIME=500
    depends_on:
      - rabbitmq
    restart: always
    
  publisher2:
    image: lab1-app:latest
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - APPLICATION_ID=publisher2
      - APPLICATION_MODE=publisher
      - PUBLISH_EVENT=Type1Event
      - PUBLISHER_TYPE=interval
      - PROCESSING_TIME=2000
    depends_on:
      - rabbitmq
    restart: always
  publisher3:
    image: lab1-app:latest
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - APPLICATION_ID=publisher3
      - APPLICATION_MODE=publisher
      - PUBLISH_EVENT=Type1Event
      - PUBLISHER_TYPE=interval
      - PROCESSING_TIME=5000
    depends_on:
      - rabbitmq
    restart: always
  publisher4:
    image: lab1-app:latest
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - APPLICATION_ID=publisher4
      - APPLICATION_MODE=publisher
      - PUBLISH_EVENT=Type2Event
      - PUBLISHER_TYPE=randomInterval
      # - PROCESSING_TIME=5000
    depends_on:
      - rabbitmq
    restart: always
  publisher5:
    image: lab1-app:latest
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - APPLICATION_ID=publisher5
      - APPLICATION_MODE=publisher
      - PUBLISH_EVENT=Type3Event
      - PUBLISHER_TYPE=randomInterval
      # - PROCESSING_TIME=5000
    depends_on:
      - rabbitmq
    restart: always

  consumer1:
    image: lab1-app:latest
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - APPLICATION_ID=consumer1
      - APPLICATION_MODE=consumer
      - CONSUME_EVENT=Type1Event
      - PROCESSING_TIME=700
    depends_on:
      - rabbitmq
    restart: always

  consumer2:
    image: lab1-app:latest
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - APPLICATION_ID=consumer2
      - APPLICATION_MODE=consumer
      - CONSUME_EVENT=Type1Event
      - PROCESSING_TIME=2000
    depends_on:
      - rabbitmq
    restart: always

  consumer3:
    image: lab1-app:latest
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - APPLICATION_ID=consumer3
      - APPLICATION_MODE=consumer
      - CONSUME_EVENT=Type2Event
      - PROCESSING_TIME=5000
    depends_on:
      - rabbitmq
    restart: always
  consumerPublisher:
    image: lab1-app:latest
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - APPLICATION_ID=consumerPublisher
      - APPLICATION_MODE=publishAfterConsume
      - CONSUME_EVENT=Type3Event
      - PUBLISH_EVENT=Type4Event
      - PROCESSING_TIME=1000
    depends_on:
      - rabbitmq
    restart: always
  consumer4:
    image: lab1-app:latest
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - APPLICATION_ID=consumer4
      - APPLICATION_MODE=consumer
      - CONSUME_EVENT=Type4Event
      - PROCESSING_TIME=1200
    depends_on:
      - rabbitmq
    restart: always
