openapi: 3.0.3
info:
  title: User Management Service API
  version: 1.0.0
  description: Manages full user profiles and credentials.

paths:
  /users/{id}:
    get:
      summary: Get full user profile by ID
      operationId: getFullUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User profile found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUserDto'
        '404':
          description: User not found

components:
  schemas:
    # DTO for REST API
    FullUserDto:
      type: object
      required:
        - userId
        - email
        - password
        - createdAt
      properties:
        userId:
          type: string
          format: uuid
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time

    # Event consumed from user-service
    UserRegisteredEvent:
      x-event: true
      type: object
      required:
        - userId
        - email
        - password
        - createdAt
      properties:
        userId:
          type: string
          format: uuid
        email:
          type: string
          format: email
        password:
          type: string
        createdAt:
          type: string
          format: date-time

    # Event emitted by user-man-service
    UserCreatedEvent:
      x-event: true
      type: object
      required:
        - userId
        - email
        - createdAt
      properties:
        userId:
          type: string
          format: uuid
        email:
          type: string
          format: email
        createdAt:
          type: string
          format: date-time
