openapi: 3.0.3
info:
  title: Notification Service API
  version: 1.0.0
  description: >
    Service responsible for sending user-facing notifications (e.g., welcome emails, role assignment alerts).
    Consumes events from RabbitMQ and uses MinIO for email templates.

paths:
  /notifications/test-send:
    post:
      summary: Send test notification (DEV only)
      operationId: testSendNotification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestNotificationRequest'
      responses:
        '200':
          description: Notification sent successfully
        '500':
          description: Failed to send notification

components:
  schemas:
    TestNotificationRequest:
      type: object
      required:
        - to
        - template
        - variables
      properties:
        to:
          type: string
          format: email
        template:
          type: string
          example: welcome/en.html
        variables:
          type: object
          additionalProperties:
            type: string
          example:
            userName: Karol
            role: ROLE_USER

    # Consumed Event - UserCreated
    UserCreatedEvent:
      x-event: true
      type: object
      required:
        - userId
        - email
        - createdAt
      properties:
        userId:
          type: string
          format: uuid
        email:
          type: string
          format: email
        createdAt:
          type: string
          format: date-time

    # Consumed Event - RoleAssigned
    RoleAssignedEvent:
      x-event: true
      type: object
      required:
        - userId
        - email
        - roles
      properties:
        userId:
          type: string
          format: uuid
        email:
          type: string
        roles:
          type: array
          items:
            type: string
          example: [ "ROLE_USER" ]
